name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: '18'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build src/AWS/Lambda/authenticate/put.ts -o dist/AWS/Lambda/authenticate/
          npx ncc build src/AWS/Lambda/package/post.ts -o dist/AWS/Lambda/package/
          npx ncc build src/AWS/Lambda/package/byName/delete.ts -o dist/AWS/Lambda/package/byName/
          npx ncc build src/AWS/Lambda/package/byName/get.ts -o dist/AWS/Lambda/package/byName/
          npx ncc build src/AWS/Lambda/package/byRegEx/post.ts -o dist/AWS/Lambda/package/byRegEx/
          npx ncc build src/AWS/Lambda/package/id/rate/get.ts -o dist/AWS/Lambda/package/id/rate/
          npx ncc build src/AWS/Lambda/packages/post.ts -o dist/AWS/Lambda/packages/
          npx ncc build src/AWS/Lambda/reset/delete.ts -o dist/AWS/Lambda/reset/

          zip dist/AWS/Lambda/deploy/authenticate-put.zip dist/AWS/Lambda/authenticate/put.js
          zip dist/AWS/Lambda/deploy/package-post.zip dist/AWS/Lambda/package/post.js
          zip dist/AWS/Lambda/deploy/package-byName-delete.zip dist/AWS/Lambda/package/byName/delete.js
          zip dist/AWS/Lambda/deploy/package-byName-get.zip dist/AWS/Lambda/package/byName/get.js
          zip dist/AWS/Lambda/deploy/package-byRegEx-post.zip dist/AWS/Lambda/package/byRegEx/post.js
          zip dist/AWS/Lambda/deploy/package-id-rate-get.zip dist/AWS/Lambda/package/id/rate/get.js
          zip dist/AWS/Lambda/deploy/packages-post.zip dist/AWS/Lambda/packages/post.js
          zip dist/AWS/Lambda/deploy/reset-delete.zip dist/AWS/Lambda/reset/delete.js

          aws lambda update-function-code --function-name=authenticate-put --zip-file=fileb:/dist/AWS/Lambda/deloy/authenticate-put.zip
          aws lambda update-function-code --function-name=package-post --zip-file=fileb:/dist/AWS/Lambda/deloy/package-post.zip
          aws lambda update-function-code --function-name=package-byName-delete --zip-file=fileb:/dist/AWS/Lambda/deloy/package-byName-delete.zip
          aws lambda update-function-code --function-name=package-byName-get --zip-file=fileb:/dist/AWS/Lambda/deloy/package-byName-get.zip
          aws lambda update-function-code --function-name=package-byRegEx-post --zip-file=fileb:/dist/AWS/Lambda/deloy/package-byRegEx-post.zip
          aws lambda update-function-code --function-name=package-id-rate-get --zip-file=fileb:/dist/AWS/Lambda/deloy/package-id-rate-get .zip
          aws lambda update-function-code --function-name=packages/post --zip-file=fileb:/dist/AWS/Lambda/deloy/packages/post.zip
          aws lambda update-function-code --function-name=reset-delete --zip-file=fileb:/dist/AWS/Lambda/deloy/reset-delete.zip